version: '3.3'

services:

  bank-processor:
    image: bank_processor:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"

  bank-operator:
    image: bank_operator:latest
    build:
      context: ../bank-operator/.
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
